version: '3'

services:
  sanic:
    image:  ubergarm/sanic-alpine
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app/static
    command: server.py

networks:
  web:
