version: '3'

services:
  sanic:
    image: sanicframework/sanic:LTS
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ${SANIC_PATH}/static:/usr/src/app/static
      - ${SANIC_PATH}/server.py:/usr/src/app/server.py
    command: python3 server.py

networks:
  default:
    external:
      name: web
