version: '3'

services:
  # https://github.com/matrix-org/synapse/blob/master/contrib/docker/docker-compose.yml
  synapse:
    image: docker.io/matrixdotorg/synapse:latest
    hostname: synapse
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - SYNAPSE_SERVER_NAME=catwebm.com #${FQDN}
      - SYNAPSE_REPORT_STATS=yes
    volumes:
      - ./files:/data
    ports:
      - "8008:8008"
    labels:
      - traefik.enable=true
      - traefik.http.routers.http-synapse.entryPoints=http
      - traefik.http.routers.http-synapse.rule=Host(`catwebm.com`)
      - traefik.http.middlewares.https_redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https_redirect.redirectscheme.permanent=true
      - traefik.http.routers.http-synapse.middlewares=https_redirect
      - traefik.http.routers.https-synapse.entryPoints=https
      - traefik.http.routers.https-synapse.rule=Host(`catwebm.com`)
      - traefik.http.routers.https-synapse.service=synapse
      - traefik.http.routers.https-synapse.tls=true
      - traefik.http.services.synapse.loadbalancer.server.port=8008
      - traefik.http.routers.https-synapse.tls.certResolver=le-ssl
    depends_on:
      - db
    networks:
      - web

networks:
  web:
