version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ${NGINX_PATH:-.}/data/nginx:/etc/nginx/conf.d
      - ${NGINX_PATH:-.}/data/certbot/conf:/etc/letsencrypt
      - ${NGINX_PATH:-.}/data/certbot/www:/var/www/certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ${NGINX_PATH:-.}/data/certbot/conf:/etc/letsencrypt
      - ${NGINX_PATH:-.}/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  default:
    external:
      name: web
