version: '3'

services:

  db:
    image: docker.io/postgres:10-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=matrix
      - POSTGRES_PASSWORD=some-pass #${POSTGRES_PASSWORD}
      - POSTGRES_DB=matrix
      # ensure the database gets created correctly
      # https://github.com/matrix-org/synapse/blob/master/docs/postgres.md#set-up-database
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./schemas:/var/lib/postgresql/data
    networks:
      - web
